USE olist_ecommerce;


-- ===============================================================================================
-- 1. SALES ANALYSIS
-- ===============================================================================================

-- Total Revenue  
-- (Calculate the total revenue generated by the platform from all the completed orders)
	SELECT ROUND(SUM(price),2) AS total_revenue
	FROM order_items;

-- Total Number of Orders
-- (Counts the total numbers of orders placed on the platform)
	SELECT COUNT(*) AS total_orders
	FROM orders;

-- Average Order Value (AOV)
-- (Measures the average amount spent per order to understand customer spending behaviour)
	SELECT ROUND(SUM(price)/COUNT(DISTINCT order_id),2) AS avg_order_value
	FROM order_items;

-- Top 10 Product Category Sales by Sales Volume
-- (Identifies the product categories with the highest number of items sold, helping understand which types of products are the most popular on the platform)
	SELECT
	p.product_category_name,
	COUNT(oi.product_id) AS total_items_sold
	FROM order_items oi
	JOIN products p
	ON oi.product_id = p.product_id
	GROUP BY p.product_category_name
	ORDER BY total_items_sold DESC
	LIMIT 10;

-- Top 10 Product Category by Revenue
-- (Identifies the product categories generating the highest revenue)
	SELECT
	p.product_category_name,
	ROUND(SUM(oi.price),2) AS revenue
	FROM order_items oi
	JOIN products p
	ON oi.product_id = p.product_id
	GROUP BY p.product_category_name
	ORDER BY revenue DESC
	LIMIT 10;

-- Monthly Order Trend
-- (Shows how the number o orders changes over time to analyze customer purchasing patterns and seasonal demand)
	SELECT
	DATE_FORMAT(order_purchase_timestamp,'%Y-%m') AS month,
	COUNT(order_id) AS total_orders
	FROM orders
	GROUP BY month
	ORDER BY month;

-- Monthly Revenue Trend
-- (Display how total revenue varies month-by-month to understand the platform's sales growth and revenue fluctuations over time)
	SELECT
	DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m') AS month,
	ROUND(SUM(oi.price),2) AS revenue
	FROM orders o
	JOIN order_items oi
	ON o.order_id = oi.order_id
	GROUP BY month
	ORDER BY month;



-- ===============================================================================================
-- 2. CUSTOMER ANALYSIS
-- ===============================================================================================

-- Total Unique Customers
-- (Calculates the total number of unique customers using the patform)
	SELECT COUNT(DISTINCT customer_unique_id) AS total_customers
	FROM customers;

-- Customers by State
-- (Shows geographic distribution of customers across diffrent states)
	SELECT
	customer_state,
	COUNT(customer_id) AS total_customers
	FROM customers
	GROUP BY customer_state
	ORDER BY total_customers DESC;

-- Top Cities by Number of Customers
-- (Identifies cities with the highest concentration of customers)
	SELECT
	customer_city,
	COUNT(customer_id) AS total_customers
	FROM customers
	GROUP BY customer_city
	ORDER BY total_customers DESC
	LIMIT 10;

-- Customers with Most Orders
-- (Identifies customers who have placed the highest number of orders, helping understand highly active buyers on the platform)
	SELECT
	c.customer_unique_id,
	COUNT(o.order_id) AS total_orders
	FROM customers c
	JOIN orders o
	ON c.customer_id = o.customer_id
	GROUP BY c.customer_unique_id
	ORDER BY total_orders DESC
	LIMIT 10;

-- Average Review Score by Customers
-- (Calculate the average rating given by cutomer to evaluate overall customer satisfaction and revieing behaviour)
	SELECT
	AVG(review_score) AS avg_review_score
	FROM order_reviews;



-- ===============================================================================================
-- 3. SELLER ANALYSIS
-- ===============================================================================================

-- Total Sellers
-- (Counts the number of sellers active on the platform)
	SELECT COUNT(*) AS total_sellers
	FROM sellers;

-- Sellers by State
-- (Shows the geographic distribution of sellers across different states to understand where most sellers are located)
	SELECT
	seller_state,
	COUNT(seller_id) AS total_sellers
	FROM sellers
	GROUP BY seller_state
	ORDER BY total_sellers DESC;

-- Top 10 Sellers by Revenue
-- (Identifies the top 10 sellers generating the highest revenue through product sales)
	SELECT
	seller_id,
	ROUND(SUM(price),2) AS revenue
	FROM order_items
	GROUP BY seller_id
	ORDER BY revenue DESC
	LIMIT 10;

-- Top Sellers by Number of Products Sold
-- (Identifies sellers who have sold the highest number of products, indicating their sales volume and activity on the platform)
	SELECT
	seller_id,
	COUNT(product_id) AS total_products_sold
	FROM order_items
	GROUP BY seller_id
	ORDER BY total_products_sold DESC
	LIMIT 10;

-- Average Revenue per Seller
-- (Calculates the average revenue generated by each seller to evaluate overall seller performance on the platform)
	SELECT
	ROUND(AVG(seller_revenue),2) AS avg_seller_revenue
	FROM (
	SELECT seller_id,
	SUM(price) AS seller_revenue
	FROM order_items
	GROUP BY seller_id
	) AS seller_stats;



-- ===============================================================================================
-- 4. DELIVERY & LOGISTICS ANALYSIS
-- ===============================================================================================

-- Average Delivery Time
-- (Calculates the average number of days taken to deliver orders)
	SELECT
	AVG(DATEDIFF(order_delivered_customer_date, order_purchase_timestamp)) AS avg_delivery_days
	FROM orders
	WHERE order_delivered_customer_date IS NOT NULL;

-- Delayed Deliveries
-- (Measures how many orders were delivered ater the estimated delivery date)
	SELECT
	COUNT(*) AS delayed_orders
	FROM orders
	WHERE order_delivered_customer_date > order_estimated_delivery_date;

-- On-Time Deliveries
-- (Measures the number of orders delivered on or before the estimated delivery date to assess delivery reliability)
	SELECT
	COUNT(*) AS on_time_orders
	FROM orders
	WHERE order_delivered_customer_date <= order_estimated_delivery_date;

-- Average Shipping Cost
-- (Calculates the average shipping cost per order to understand the typical logistics expense for deliveries)
	SELECT
	ROUND(AVG(freight_value),2) AS avg_shipping_cost
	FROM order_items;

-- Delivery Time by State
-- (Analyzes delivery efficiency across different regions)
	SELECT
	c.customer_state,
	AVG(DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp)) AS avg_delivery_days
	FROM orders o
	JOIN customers c
	ON o.customer_id = c.customer_id
	WHERE o.order_delivered_customer_date IS NOT NULL
	GROUP BY c.customer_state
	ORDER BY avg_delivery_days DESC;



-- ===============================================================================================
-- 5. ADVANCED ANALYSIS
-- ===============================================================================================

-- Number of Repeat Customers vs One-Time Customers
-- (Comapres customers who placed multiple orders with those who made only a single purchase to evaluate customer retention)
	SELECT
	CASE
	WHEN order_count = 1 THEN 'One-time customer'
	ELSE 'Repeat customer'
	END AS customer_type,
	COUNT(*) AS total_customers
	FROM
	(
	SELECT
	c.customer_unique_id,
	COUNT(o.order_id) AS order_count
	FROM customers c
	JOIN orders o
	ON c.customer_id = o.customer_id
	GROUP BY c.customer_unique_id
	) AS customer_orders
	GROUP BY customer_type;

-- Customer Lifetime Value (Top Customers)
-- (Estimates the total revenue generated by each customer over all their purchases on the platform)
	SELECT
	c.customer_unique_id,
	ROUND(SUM(oi.price),2) AS total_spent
	FROM customers c
	JOIN orders o
	ON c.customer_id = o.customer_id
	JOIN order_items oi
	ON o.order_id = oi.order_id
	GROUP BY c.customer_unique_id
	ORDER BY total_spent DESC
	LIMIT 10;

-- Revenue by City
-- (Shows which cities generate the highest revenue, helping identify key geographic markets)
	SELECT
	c.customer_city,
	ROUND(SUM(oi.price),2) AS revenue
	FROM customers c
	JOIN orders o
	ON c.customer_id = o.customer_id
	JOIN order_items oi
	ON o.order_id = oi.order_id
	GROUP BY c.customer_city
	ORDER BY revenue DESC
	LIMIT 10;

-- Impact of Delivery Time on Review Score
-- (Analyzes how delivery duration influences customer review scores and satisfaction levels)
	SELECT
	AVG(DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp)) AS avg_delivery_days,
	AVG(r.review_score) AS avg_review_score
	FROM orders o
	JOIN order_reviews r
	ON o.order_id = r.order_id
	WHERE o.order_delivered_customer_date IS NOT NULL;

-- Best Product Category per State
-- (Identifies the product category generating the highest revenue or sales within each state)
	SELECT
	c.customer_state,
	p.product_category_name,
	COUNT(*) AS sales
	FROM orders o
	JOIN customers c
	ON o.customer_id = c.customer_id
	JOIN order_items oi
	ON o.order_id = oi.order_id
	JOIN products p
	ON oi.product_id = p.product_id
	GROUP BY c.customer_state, p.product_category_name
	ORDER BY sales DESC;

-- Seller Delivery Performance
-- (Evaluates sellers based on delivery efficiency, typically using delivery time or on-time delivery rate)
	SELECT
	oi.seller_id,
	AVG(DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp)) AS avg_delivery_days
	FROM order_items oi
	JOIN orders o
	ON oi.order_id = o.order_id
	WHERE o.order_delivered_customer_date IS NOT NULL
	GROUP BY oi.seller_id
	ORDER BY avg_delivery_days;
    
-- ===============================================================================================

